// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY0GRvMa6ObcwkyJOKc98TsmUchh1J4oY',
    appId: '1:429304281692:web:8ea615996425ae594f4499',
    messagingSenderId: '429304281692',
    projectId: 'myanlib-dev',
    authDomain: 'myanlib-dev.firebaseapp.com',
    storageBucket: 'myanlib-dev.appspot.com',
    measurementId: 'G-ZEHX1QW34D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkFjzltVksmD7w46er7UZ9QpzcSvNKWGk',
    appId: '1:429304281692:android:f3b4b7142983afee4f4499',
    messagingSenderId: '429304281692',
    projectId: 'myanlib-dev',
    storageBucket: 'myanlib-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPaZiFo-zF2YHmdjulRSo2Q6LafTpTiag',
    appId: '1:429304281692:ios:c847b8ea218a45a44f4499',
    messagingSenderId: '429304281692',
    projectId: 'myanlib-dev',
    storageBucket: 'myanlib-dev.appspot.com',
    iosBundleId: 'com.tech4mm.myanLibDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPaZiFo-zF2YHmdjulRSo2Q6LafTpTiag',
    appId: '1:429304281692:ios:c847b8ea218a45a44f4499',
    messagingSenderId: '429304281692',
    projectId: 'myanlib-dev',
    storageBucket: 'myanlib-dev.appspot.com',
    iosBundleId: 'com.tech4mm.myanLibDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY0GRvMa6ObcwkyJOKc98TsmUchh1J4oY',
    appId: '1:429304281692:web:31cb62047fb0c9b14f4499',
    messagingSenderId: '429304281692',
    projectId: 'myanlib-dev',
    authDomain: 'myanlib-dev.firebaseapp.com',
    storageBucket: 'myanlib-dev.appspot.com',
    measurementId: 'G-HD3W2D6SZF',
  );
}
